### ISSUE TITLE
npm install failed for node sass on windows 10

### ISSUE THREAD

**Issue by prashantalhat** [jpsierens/webpack-react-redux-react-router#36]
Hi,
I am facing this issue when performing npm install, particularly for node-sass module.

`gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\pocs\webpack-react-redux\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\pocs\webpack-react-redux\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\pocs\webpack-react-redux\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\pocs\webpack-react-redux\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\pocs\webpack-react-redux\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\pocs\webpack-react-redux\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\pocs\webpack-react-redux\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\pocs\webpack-react-redux\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\pocs\webpack-react-redux\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\pocs\webpack-react-redux\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\pocs\webpack-react-redux\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\pocs\webpack-react-redux\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:152:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\pocs\\webpack-react-redux\\node_modules\\which\\which.js:13:12)\n    at F (C:\\pocs\\webpack-react-redux\\node_modules\\which\\which.js:68:19)\n    at E (C:\\pocs\\webpack-react-redux\\node_modules\\which\\which.js:80:29)\n    at C:\\pocs\\webpack-react-redux\\node_modules\\which\\which.js:89:16\n    at C:\\pocs\\webpack-react-redux\\node_modules\\isexe\\index.js:42:5\n    at C:\\pocs\\webpack-react-redux\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:152:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\Prashant Alhat\AppData\Local\Programs\Python\Python36-32\python.EXE
gyp verb check python version `C:\Users\Prashant Alhat\AppData\Local\Programs\Python\Python36-32\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.4\r\n"`

**Comment by prashantalhat** [comment]
I have a solution for this. I just updated node sass module to latest version i.e. 4.8.3 which fixed my issue.
